server:
  port: 8060

app:
  jwt:
    secret: ${JWT_SECRET}

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:8100"
              - "http://192.168.1.101:8100"
              - "http://localhost"
              - "capacitor://localhost"
              - "https://projectmirror.tech"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: auth-service-route
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: defaultCircuitBreaker

        - id: memory-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/memory/**,/api/admin/memory/**
          filters:
            - AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userKeyResolver}"
            - name: CircuitBreaker
              args:
                name: defaultCircuitBreaker

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus, circuitbreakers
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}

resilience4j:
  timelimiter:
    instances:
      defaultCircuitBreaker:
        timeoutDuration: 60s
  circuitbreaker:
    instances:
      defaultCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3



---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "https://projectmirror.tech"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service-route
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: defaultCircuitBreaker

        - id: memory-service-route
          uri: ${MEMORY_SERVICE_URL}
          predicates:
            - Path=/api/memory/**,/api/admin/memory/**
          filters:
            - AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userKeyResolver}"
            - name: CircuitBreaker
              args:
                name: defaultCircuitBreaker
