server:
  port: 8060

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8100"
              - "http://192.168.1.101:8100"
              - "http://localhost"
              - "capacitor://localhost"
              - "https://projectmirror.tech"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: memory-service-route
          uri: lb://memory-service
          predicates:
            - Path=/api/memory/**

management:
  endpoints:
    web:
      exposure:
        include: info, health

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    registry-fetch-interval-seconds: 5
  service-url:
    defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "https://projectmirror.tech"
              - "http://localhost:8100"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service-route
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/auth/**

eureka:
  client:
    enabled: false